# Licensed to Tomitribe Corporation under the Apache License, Version 2.0.
# Main build: compile the project and run tests.
# The process goal (bound to initialize) transforms the jar.
# The test phase exercises the instrumented dependency.
invoker.goals = test
