/*
 * Licensed to Tomitribe Corporation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership. Tomitribe Corporation licenses
 * this file to You under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
package org.tomitribe.jackknife.plugin;

import org.apache.maven.artifact.Artifact;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.plugins.annotations.ResolutionScope;
import org.apache.maven.project.MavenProject;
import org.tomitribe.jackknife.index.IndexWriter;
import org.tomitribe.jackknife.scanner.JarScanner;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Set;

/**
 * Scans all resolved dependencies and builds structural index files
 * in .jackknife/index/. Also generates USAGE.md.
 */
@Mojo(name = "index", requiresDependencyResolution = ResolutionScope.COMPILE_PLUS_RUNTIME, aggregator = true)
public class IndexMojo extends AbstractMojo {

    @Parameter(defaultValue = "${project}", readonly = true, required = true)
    private MavenProject project;

    @Parameter(defaultValue = "${session.executionRootDirectory}", readonly = true)
    private String executionRootDirectory;

    @Override
    public void execute() throws MojoExecutionException, MojoFailureException {
        final File rootDir = new File(executionRootDirectory);
        final File jackknife = new File(rootDir, ".jackknife");
        final File indexDir = new File(jackknife, "index");

        indexDir.mkdirs();

        final Set<Artifact> artifacts = project.getArtifacts();
        int indexed = 0;
        int skipped = 0;

        for (final Artifact artifact : artifacts) {
            final File file = artifact.getFile();

            if (file == null || !file.exists() || !file.getName().endsWith(".jar")) {
                skipped++;
                continue;
            }

            final String groupId = artifact.getGroupId();
            final String fileName = file.getName();
            final String indexFileName = fileName + ".index";

            final File groupDir = new File(indexDir, groupId);
            final File indexFile = new File(groupDir, indexFileName);

            // SNAPSHOT invalidation: re-index if jar is newer than index
            if (indexFile.exists() && indexFile.lastModified() >= file.lastModified()) {
                getLog().debug("Index up to date: " + indexFile.getName());
                skipped++;
                continue;
            }

            try {
                getLog().info("Indexing " + artifact.getGroupId() + ":" + artifact.getArtifactId() + ":" + artifact.getVersion());
                final JarScanner.Result result = JarScanner.scan(file);
                IndexWriter.write(result, indexFile);
                indexed++;
            } catch (final IOException e) {
                getLog().warn("Failed to index " + file.getName() + ": " + e.getMessage());
                skipped++;
            }
        }

        getLog().info("Indexed " + indexed + " jars, skipped " + skipped + " (up to date or non-jar)");

        // Generate USAGE.md
        try {
            writeUsage(jackknife);
        } catch (final IOException e) {
            throw new MojoExecutionException("Failed to write USAGE.md", e);
        }
    }

    private void writeUsage(final File jackknife) throws IOException {
        final File usageFile = new File(jackknife, "USAGE.md");

        try (final PrintWriter out = new PrintWriter(new FileWriter(usageFile))) {
            out.println("<!-- DO NOT EDIT — generated by jackknife-maven-plugin. Regenerated on every `mvn jackknife:index`. -->");
            out.println();
            out.println("# Jackknife Usage");
            out.println();
            out.println("## Quick Start");
            out.println();
            out.println("Index files have been generated in `.jackknife/index/`. Use Grep to search them directly — no Maven needed.");
            out.println();
            out.println("## Directory Structure");
            out.println();
            out.println("```");
            out.println(".jackknife/");
            out.println("├── index/                   Index files (greppable, one per jar)");
            out.println("│   └── <groupId>/");
            out.println("│       └── <artifact>-<version>.jar.index");
            out.println("├── source/                  Cached decompiled source");
            out.println("│   └── <groupId>/");
            out.println("│       └── <ClassName>.java");
            out.println("├── instrument/              Instrumentation inbox (write configs here)");
            out.println("│   └── <groupId>/");
            out.println("│       └── <artifact>-<version>.jar.properties");
            out.println("├── modified/                Patched jars + moved configs (receipts)");
            out.println("│   └── <groupId>/");
            out.println("│       ├── <artifact>-<version>.jar");
            out.println("│       └── <artifact>-<version>.jar.properties");
            out.println("└── USAGE.md                 This file (regenerated, do not edit)");
            out.println("```");
            out.println();
            out.println("## Index File Format");
            out.println();
            out.println("Each `.index` file is flat text, one class per block, blank-line separated.");
            out.println();
            out.println("```");
            out.println("# com.example.MyClass");
            out.println("public class com.example.MyClass extends com.example.AbstractBase");
            out.println("implements java.io.Serializable");
            out.println("@jakarta.inject.Named");
            out.println("  private final field name : java.lang.String");
            out.println("  public method process(java.lang.String input, int count) : boolean");
            out.println("    declares java.io.IOException");
            out.println("    throws java.lang.IllegalArgumentException");
            out.println("  public static method getInstance() : com.example.MyClass");
            out.println("```");
            out.println();
            out.println("Resources are listed at the end under `# resources`.");
            out.println();
            out.println("## Common Grep Patterns");
            out.println();
            out.println("Find a class by name:");
            out.println("```");
            out.println("grep -r 'DefaultRetryHandler' .jackknife/index/");
            out.println("```");
            out.println();
            out.println("Find all implementations of an interface:");
            out.println("```");
            out.println("grep -r 'implements.*HttpRequestRetryHandler' .jackknife/index/");
            out.println("```");
            out.println();
            out.println("Find all classes with an annotation:");
            out.println("```");
            out.println("grep -r '@jakarta.ejb.Stateless' .jackknife/index/");
            out.println("```");
            out.println();
            out.println("Find methods that throw a specific exception:");
            out.println("```");
            out.println("grep -r 'throws.*IllegalStateException' .jackknife/index/");
            out.println("```");
            out.println();
            out.println("Find a resource file:");
            out.println("```");
            out.println("grep -r 'META-INF/services' .jackknife/index/");
            out.println("```");
            out.println();
            out.println("## Decompiling");
            out.println();
            out.println("To see the full source of a class:");
            out.println("```");
            out.println("mvn jackknife:decompile -Dclass=com.example.MyClass");
            out.println("```");
            out.println();
            out.println("Decompiled source is cached in `.jackknife/source/` for repeat access.");
            out.println();
            out.println("## Instrumenting");
            out.println();
            out.println("To instrument a method for runtime observation:");
            out.println("```");
            out.println("mvn jackknife:instrument -Dmethod=\"com.example.Foo.process(String, int)\" -Dmode=debug");
            out.println("```");
            out.println();
            out.println("Modes:");
            out.println("- `debug` — logs method entry (args), exit (return value), and any thrown exceptions");
            out.println("- `timing` — logs elapsed time only (lightweight, no value capture)");
            out.println();
            out.println("The method parser is forgiving — you can paste from index output or use shorthand.");
            out.println("Method-name-only targets all matching methods across classes.");
            out.println();
            out.println("Instrumented jars are applied automatically on the next build.");
            out.println("Remove from `.jackknife/modified/` to revert.");
        }

        getLog().info("Generated " + usageFile.getPath());
    }
}
