# Licensed to Tomitribe Corporation under the Apache License, Version 2.0.
# Main build: compile, process instrumented dependency, run tests.
# Prebuild leaves className+methodName config (all overloads of join).
invoker.goals = test
