# Licensed to Tomitribe Corporation under the Apache License, Version 2.0.
# Second run of decompile — should use cached source.
invoker.goals = jackknife:decompile -Dclass=org.tomitribe.jackknife.runtime.DebugHandler
